global:
    scrape_interval:     15s
    evaluation_interval: 15s

rule_files:

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['127.0.0.1:9090']

    - job_name: 'cats-api'
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
      - targets:
        - 'cats-api:8000'
        labels:
          alias: "cats-api"